site_name: Документация интернет-магазина
site_description: Документация для проекта интернет-магазина с поддержкой множества поставщиков
site_author: Разработчик

repo_url: https://github.com/username/myproject
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

nav:
  - Главная: index.md
  - Архитектура: architecture.md
  - Модели: models.md
  - API: api.md
  - Celery: celery.md
  - Развертывание: deployment.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username/myproject
    - icon: fontawesome/brands/python
      link: https://www.python.org/